// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TaGiang.OneDay
{

    internal partial class OneDay
    {
        internal class Clouds2
        {

            [JsonProperty("all")]
            public int All { get; set; }
        }
    }

}
