// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Example
{

    internal partial class WeekDay
    {
        internal class Temp2
        {

            [JsonProperty("day")]
            public double Day { get; set; }

            [JsonProperty("min")]
            public double Min { get; set; }

            [JsonProperty("max")]
            public double Max { get; set; }

            [JsonProperty("night")]
            public double Night { get; set; }

            [JsonProperty("eve")]
            public double Eve { get; set; }

            [JsonProperty("morn")]
            public double Morn { get; set; }
        }
    }

}
