// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Example
{

    internal partial class WeekDay
    {
        internal class List2
        {

            [JsonProperty("dt")]
            public int Dt { get; set; }

            [JsonProperty("temp")]
            public Temp2 Temp { get; set; }

            [JsonProperty("pressure")]
            public double Pressure { get; set; }

            [JsonProperty("humidity")]
            public int Humidity { get; set; }

            [JsonProperty("weather")]
            public Weather2[] Weather { get; set; }

            [JsonProperty("speed")]
            public double Speed { get; set; }

            [JsonProperty("deg")]
            public int Deg { get; set; }

            [JsonProperty("clouds")]
            public int Clouds { get; set; }

            [JsonProperty("rain")]
            public double Rain { get; set; }
        }
    }

}
