// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Example
{

    internal partial class WeekDay
    {
        internal class City2
        {

            [JsonProperty("id")]
            public string Id { get; set; }

            [JsonProperty("name")]
            public string Name { get; set; }

            [JsonProperty("coord")]
            public Coord2 Coord { get; set; }

            [JsonProperty("country")]
            public string Country { get; set; }

            [JsonProperty("population")]
            public int Population { get; set; }
        }
    }

}
