// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TaGiang.OneDay
{

    internal partial class OneDay
    {

        [JsonProperty("coord")]
        public Coord2 Coord { get; set; }

        [JsonProperty("sys")]
        public Sys2 Sys { get; set; }

        [JsonProperty("weather")]
        public Weather2[] Weather { get; set; }

        [JsonProperty("base")]
        public string Base { get; set; }

        [JsonProperty("main")]
        public Main2 Main { get; set; }

        [JsonProperty("wind")]
        public Wind2 Wind { get; set; }

        [JsonProperty("clouds")]
        public Clouds2 Clouds { get; set; }

        [JsonProperty("rain")]
        public Rain2 Rain { get; set; }

        [JsonProperty("dt")]
        public int Dt { get; set; }

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("cod")]
        public int Cod { get; set; }
    }

}
